# Load the manifest from the specified source into a temporary file
# Fail if the file is empty

- name: "{{ name_header }} : Set temporary file path"
  tempfile:
    state: file
    prefix: kubernetes-crud-rendered-manifest-
  register: resource_tempfile

- name: "{{ name_header }} : Load manifest as url"
  when: manifest_url != "" # noqa 602
  get_url:
    force: true
    url: "{{ manifest_url }}"
    dest: "{{ resource_tempfile.path }}"
  register: result

- name: "{{ name_header }} : Load manifest as file"
  copy:
    src: '{{ manifest_base }}/{{ manifest_path }}'
    dest: '{{ resource_tempfile.path }}'
    force: yes
    mode: 0600
  when: manifest_path != "" # noqa 602

- name: "{{ name_header }} : Load manifest as template"
  when: manifest_template_path != "" # noqa 602
  template:
    src: "{{ manifest_base }}/{{ manifest_template_path }}"
    dest: "{{ resource_tempfile.path }}"
    mode: 0600

- name: "{{ name_header }} : Render inline template"
  when: manifest_inline != "" # noqa 602
  copy:
    content: "{{ manifest_inline }}"
    dest: "{{ resource_tempfile.path }}"
    mode: 0600

- name: "{{ name_header }} : stat source file"
  stat:
    path: "{{ resource_tempfile.path }}"
  register: resource

- name: "{{ name_header }} : Fail if resource file is empty"
  fail:
    msg: "Invalid manifest source"
  when: resource.stat.size == 0
