- name: "{{ name_header }} : invoke kubectl"
  k8s:
      kubeconfig: '{{ _kubeconfig_path }}'
      context: '{{ _context }}'
      state: present
      kind: Namespace
      name: "{{ namespace }}"
      validate:
          fail_on_error: "{{ fatal_validation }}"
          strict: "{{ strict_validation }}"
