- name: "{{ name_header }} : invoke kubectl (wait to confim deletion)"
  k8s:
    wait: true
    wait_timeout: 300
    kubeconfig: '{{ _kubeconfig_path }}'
    context: '{{ _context }}'
    state: absent
    kind: Namespace
    name: "{{ namespace }}"
    validate:
      fail_on_error: "{{ fatal_validation }}"
      strict: "{{ strict_validation }}"
