- hosts: localhost
  tasks:
    - set_fact:
        deploy_environment: '{{ lookup("env", "DEPLOY_ENVIRONMENT") }}'
    - fail:
        msg: DEPLOY_ENVIRONMENT must be set
      when: deploy_environment is undefined or deploy_environment == ""

    - name: Include staging config
      include_vars:
        file: "{{ deploy_environment }}.yaml"

    - name: Tear down kubevirtci cluster
      command: make cluster-down
      changed_when: false
      args:
        chdir: "{{ kubevirtci_dir }}"
      environment: "{{ shell_environment }}"
      when: "'kubevirtci' in deploy_environment"
