- hosts: localhost
  tasks:
    - set_fact:
        deploy_environment: '{{ lookup("env", "DEPLOY_ENVIRONMENT") }}'
    - fail:
        msg: DEPLOY_ENVIRONMENT must be set
      when: deploy_environment is undefined or deploy_environment == ""

    - name: Include Deploy config
      include_vars:
        file: "{{ deploy_environment }}.yaml"

    - name: Include smoke tests
      include_tasks: smoke_tests.yaml

