- hosts: localhost
  vars:
    kubevirtci_dir: /tmp/kubevirtci
    kubevirtci_provider: k8s-1.18
  tasks:
    - name: Clone kubevirtci repo
      git:
        repo: https://github.com/kubevirt/kubevirtci.git
        dest: "{{ kubevirtci_dir }}"
        version: master

    - name: Launch kubevirtci cluster
      command: make cluster-up
      changed_when: false
      args:
        chdir: "{{ kubevirtci_dir }}"
      environment:
        KUBEVIRT_PROVIDER: "{{ kubevirtci_provider }}"
        KUBEVIRT_NUM_NODES: 2
        KUBEVIRT_NUM_SECONDARY_NICS: 1
